### ISSUE TITLE
plugins integration suggestion

### ISSUE THREAD

**Issue by Lionardo** [fang2hou/chatbot-gpt#1]
hej @fang2hou  love your chatgpt project!👏
How about integrating getitAI's open Plugin Store for easy plugin installs? (https://www.getit.ai/gpt-plugins) Let's chat for 15 mins: https://calendly.com/d/z4j-cb5-h2y/getitai-devs

**Comment by fang2hou** [comment]
@Lionardo 
Sorry, this project is only for limited usage
